# Generated by Django 4.2.9 on 2024-02-03 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_confirmcode_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmcode',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='confirmcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
